version: '3.8'

services:
  assdoc:
    build: .
    container_name: assdoc_app
    restart: unless-stopped
    ports:
      - "3000:3000" # HTTP padrão
      - "3443:3443" # HTTPS (Webcam e câmera liberadas em qualquer dispositivo)
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - DB_PATH=/app/database
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
      - ./certs:/app/certs
